# Explore here

In [144]:
# Your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_regression

In [145]:
df = pd.read_csv('../data/raw/demographic_health_data.csv')

#### Remember: Choose independant features like age and target being Obesity

In [146]:
df.columns

Index(['fips', 'TOT_POP', '0-9', '0-9 y/o % of total pop', '19-Oct',
       '10-19 y/o % of total pop', '20-29', '20-29 y/o % of total pop',
       '30-39', '30-39 y/o % of total pop',
       ...
       'COPD_number', 'diabetes_prevalence', 'diabetes_Lower 95% CI',
       'diabetes_Upper 95% CI', 'diabetes_number', 'CKD_prevalence',
       'CKD_Lower 95% CI', 'CKD_Upper 95% CI', 'CKD_number',
       'Urban_rural_code'],
      dtype='object', length=108)

In [147]:
pd.set_option('display.max_columns', None)
df.head()

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,40-49,40-49 y/o % of total pop,50-59,50-59 y/o % of total pop,60-69,60-69 y/o % of total pop,70-79,70-79 y/o % of total pop,80+,80+ y/o % of total pop,White-alone pop,% White-alone,Black-alone pop,% Black-alone,Native American/American Indian-alone pop,% NA/AI-alone,Asian-alone pop,% Asian-alone,Hawaiian/Pacific Islander-alone pop,% Hawaiian/PI-alone,Two or more races pop,% Two or more races,POP_ESTIMATE_2018,N_POP_CHG_2018,GQ_ESTIMATES_2018,R_birth_2018,R_death_2018,R_NATURAL_INC_2018,R_INTERNATIONAL_MIG_2018,R_DOMESTIC_MIG_2018,R_NET_MIG_2018,Less than a high school diploma 2014-18,High school diploma only 2014-18,Some college or associate's degree 2014-18,Bachelor's degree or higher 2014-18,Percent of adults with less than a high school diploma 2014-18,Percent of adults with a high school diploma only 2014-18,Percent of adults completing some college or associate's degree 2014-18,Percent of adults with a bachelor's degree or higher 2014-18,POVALL_2018,PCTPOVALL_2018,PCTPOV017_2018,PCTPOV517_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Active Physicians per 100000 Population 2018 (AAMC),Total Active Patient Care Physicians per 100000 Population 2018 (AAMC),Active Primary Care Physicians per 100000 Population 2018 (AAMC),Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC),Active General Surgeons per 100000 Population 2018 (AAMC),Active Patient Care General Surgeons per 100000 Population 2018 (AAMC),Total nurse practitioners (2019),Total physician assistants (2019),Total Hospitals (2019),Internal Medicine Primary Care (2019),Family Medicine/General Practice Primary Care (2019),Total Specialist Physicians (2019),ICU Beds_x,Total Population,Population Aged 60+,Percent of Population Aged 60+,COUNTY_NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,county_pop2018_18 and older,anycondition_prevalence,anycondition_Lower 95% CI,anycondition_Upper 95% CI,anycondition_number,Obesity_prevalence,Obesity_Lower 95% CI,Obesity_Upper 95% CI,Obesity_number,Heart disease_prevalence,Heart disease_Lower 95% CI,Heart disease_Upper 95% CI,Heart disease_number,COPD_prevalence,COPD_Lower 95% CI,COPD_Upper 95% CI,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
0,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,7582,13.636445,7738,13.917016,5826,10.478229,4050,7.284042,2014,3.622237,42660,76.725239,10915,19.630942,267,0.480207,681,1.224798,62,0.111509,1016,1.827305,55601,158,455,11.8,9.6,2.2,0.0,0.7,0.6,4204,12119,10552,10291,11.3,32.6,28.4,27.7,7587,13.8,19.3,19.5,59338,53628,65048,25957,25015,942,3.6,59338,119.0,217.1,196.7,77.2,71.2,7.6,6.9,28.859137,6.085786,1.148905,25.992561,21.249061,72.142154,6,55036,10523,19.1,Autauga,Alabama,1,1,42438,47.6,45.4,49.4,20181,35.8,34.2,37.3,15193,7.9,7.2,8.7,3345,8.6,7.3,9.9,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
1,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,27338,12.539102,29986,13.753658,29932,13.728890,20936,9.602701,9368,4.296814,190301,87.285228,19492,8.940382,1684,0.772399,2508,1.150343,146,0.066966,3891,1.784682,218022,5403,2190,10.5,10.3,0.1,0.5,24.3,24.8,14310,40579,46025,46075,9.7,27.6,31.3,31.3,21069,9.8,13.9,13.1,57588,54437,60739,93849,90456,3393,3.6,57588,115.5,217.1,196.7,77.2,71.2,7.6,6.9,113.162114,23.863512,4.505074,101.921730,83.321572,282.882982,51,203360,53519,26.3,Baldwin,Alabama,1,3,170912,40.2,38.2,42.3,68790,29.7,28.4,31.0,50761,7.8,7.0,8.7,13414,8.6,7.2,10.1,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
2,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,3074,12.354809,3278,13.174712,3076,12.362847,2244,9.018930,1048,4.212049,12209,49.069571,12042,48.398376,164,0.659137,113,0.454162,46,0.184880,307,1.233873,24881,-277,2820,10.4,12.9,-2.5,0.5,-9.1,-8.6,4901,6486,4566,2220,27.0,35.7,25.1,12.2,6788,30.9,43.9,36.7,34382,31157,37607,8373,7940,433,5.2,34382,68.9,217.1,196.7,77.2,71.2,7.6,6.9,12.914231,2.723340,0.514126,11.631462,9.508784,32.283033,5,26201,6150,23.5,Barbour,Alabama,1,5,19689,57.5,55.6,59.1,11325,40.7,39.5,41.9,8013,11.0,10.1,11.8,2159,12.1,10.7,13.3,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
3,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,3038,13.562500,3115,13.906250,2545,11.361607,1723,7.691964,785,3.504464,17211,76.834821,4770,21.294643,98,0.437500,53,0.236607,26,0.116071,242,1.080357,22400,-155,2151,11.1,11.4,-0.3,0.4,-7.0,-6.6,2650,7471,3846,1813,16.8,47.3,24.4,11.5,4400,21.8,27.8,26.3,46064,41283,50845,8661,8317,344,4.0,46064,92.3,217.1,196.7,77.2,71.2,7.6,6.9,11.626493,2.451783,0.462860,10.471635,8.560619,29.063942,0,22580,4773,21.1,Bibb,Alabama,1,7,17813,51.6,49.6,53.4,9190,38.7,37.4,40.2,6894,8.6,7.9,9.3,1533,10.0,8.8,11.3,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
4,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,7474,12.921853,7844,13.561549,6965,12.041840,4931,8.525242,2335,4.036999,55456,95.878285,950,1.642462,378,0.653527,185,0.319848,70,0.121024,801,1.384855,57840,13,489,11.8,11.4,0.3,0.1,-0.2,0.0,7861,13489,13267,5010,19.8,34.0,33.5,12.6,7527,13.2,18.0,15.5,50412,46157,54667,25006,24128,878,3.5,50412,101.1,217.1,196.7,77.2,71.2,7.6,6.9,30.021267,6.330854,1.195171,27.039257,22.104740,75.047251,6,57667,13600,23.6,Blount,Alabama,1,9,44448,46.3,44.3,48.4,20584,34.0,32.4,35.5,15112,9.2,8.4,10.1,4101,10.5,9.1,12.0,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Columns: 108 entries, fips to Urban_rural_code
dtypes: float64(61), int64(45), object(2)
memory usage: 2.6+ MB

We have 2 object types, let's see which columns have object values:

In [149]:
str_columns = []
for column in df.columns:
    # Check if the dtype of the column is 'object' (usually indicates string values)
    if df[column].dtype == 'object':
        # Append the column name to the list
        str_columns.append(column)

# Print the columns with string values
print("Columns with string values:", str_columns)

Columns with string values: ['COUNTY_NAME', 'STATE_NAME']

In [150]:
df.shape

(3140, 108)

In [151]:
df.columns

Index(['fips', 'TOT_POP', '0-9', '0-9 y/o % of total pop', '19-Oct',
       '10-19 y/o % of total pop', '20-29', '20-29 y/o % of total pop',
       '30-39', '30-39 y/o % of total pop',
       ...
       'COPD_number', 'diabetes_prevalence', 'diabetes_Lower 95% CI',
       'diabetes_Upper 95% CI', 'diabetes_number', 'CKD_prevalence',
       'CKD_Lower 95% CI', 'CKD_Upper 95% CI', 'CKD_number',
       'Urban_rural_code'],
      dtype='object', length=108)

In [152]:
df.diabetes_number

0        5462
1       20520
2        3870
3        2511
4        6017
        ...
3135     2834
3136     1360
3137     1500
3138      686
3139      644
Name: diabetes_number, Length: 3140, dtype: int64

In [153]:
df.diabetes_number.unique().tolist()

[5462,
 20520,
 3870,
 2511,
 6017,
 1651,
 2841,
 13182,
 4664,
 3353,
 5115,
 1976,
 3575,
 1732,
 1665,
 5596,
 6429,
 1994,
 1662,
 4557,
 1745,
 8840,
 5427,
 6160,
 8479,
 8072,
 4944,
 12221,
 2009,
 3496,
 3429,
 1641,
 2265,
 2272,
 12957,
 6307,
 68819,
 1823,
 9794,
 3964,
 14475,
 9737,
 1719,
 3037,
 34952,
 2804,
 3558,
 10471,
 45540,
 3235,
 27581,
 12583,
 1632,
 2883,
 3626,
 2880,
 6821,
 8914,
 17570,
 1946,
 10465,
 5377,
 19810,
 7386,
 2214,
 1770,
 2947,
 571,
 19490,
 1839,
 83,
 157,
 478,
 5756,
 223,
 260,
 2135,
 4846,
 1148,
 945,
 895,
 164,
 6996,
 903,
 814,
 739,
 278,
 705,
 658,
 77,
 562,
 263,
 70,
 663,
 8894,
 11673,
 9597,
 6121,
 3201,
 751,
 3108,
 321467,
 24750,
 12334,
 88469,
 46827,
 5440,
 23017,
 20561,
 2120,
 2529,
 4966,
 20795,
 3742,
 1355,
 679,
 3077,
 1546,
 2101,
 1692,
 2946,
 936,
 2713,
 2314,
 9386,
 6089,
 5577,
 1945,
 1011,
 1656,
 2005,
 9939,
 1979,
 1600,
 11133,
 1664,
 4056,
 2676,
 3642,
 1507,
 3520,
 2070,
 8680,
 2827,
 975,
 1759,
 1381,
 1552,
 1445,
 2401,
 5913,
 1833,
 2232,
 4719,
 5006,
 1080,
 1159,
 1104,
 968,
 3310,
 1140,
 2703,
 1212,
 2648,
 2422,
 6208,
 974,
 38634,
 1989,
 3458,
 10013,
 1305,
 1016,
 13439,
 1756,
 2328,
 1661,
 4397,
 2097,
 18103,
 7478,
 887,
 2329,
 124443,
 130,
 4054,
 19770,
 4613,
 1926,
 87571,
 2790,
 15421,
 85769,
 2494,
 11402,
 18521,
 1676,
 78504,
 12751,
 6847,
 2608,
 952335,
 14552,
 19071,
 1843,
 8749,
 24850,
 994,
 1112,
 36143,
 11153,
 8799,
 250520,
 27480,
 1864,
 215186,
 123474,
 4857,
 204266,
 251137,
 67258,
 66030,
 22537,
 58053,
 33512,
 143158,
 20316,
 15832,
 335,
 4500,
 38175,
 40587,
 44773,
 8696,
 6289,
 1492,
 42445,
 5265,
 63672,
 15603,
 6143,
 30901,
 1323,
 39382,
 1162,
 594,
 17331,
 3473,
 1654,
 140,
 680,
 867,
 577,
 498,
 2971,
 40637,
 191,
 15574,
 2987,
 1666,
 40673,
 4305,
 3592,
 415,
 1120,
 956,
 71,
 777,
 124,
 33878,
 117,
 547,
 602,
 3561,
 19166,
 1513,
 434,
 1644,
 10939,
 66,
 943,
 2321,
 3606,
 2060,
 1804,
 393,
 1422,
 319,
 1100,
 1013,
 14975,
 430,
 1521,
 760,
 65,
 488,
 215,
 1767,
 1934,
 380,
 20680,
 725,
 62779,
 72956,
 13700,
 12051,
 73592,
 22006,
 9818,
 9988,
 19351,
 49031,
 24950,
 46523,
 22543,
 2533,
 17749,
 3102,
 63982,
 201079,
 24470,
 18842,
 19664,
 43370,
 7873,
 5098,
 2126,
 98334,
 29564,
 13814,
 1411,
 6525,
 2000,
 1973,
 1806,
 1798,
 3197,
 5079,
 22310,
 15100,
 137266,
 2366,
 18745,
 6138,
 1880,
 959,
 40608,
 80680,
 22914,
 5516,
 908,
 2517,
 43242,
 47754,
 17132,
 312317,
 8036,
 7999,
 17368,
 4984,
 117345,
 37851,
 163990,
 54844,
 101883,
 75763,
 10149,
 20588,
 38342,
 15533,
 48127,
 40347,
 19838,
 5059,
 2596,
 1752,
 63668,
 6964,
 2845,
 2270,
 1028,
 1264,
 455,
 5419,
 1983,
 7046,
 9608,
 2165,
 2257,
 18916,
 1341,
 2125,
 2119,
 2712,
 6872,
 2894,
 2884,
 1010,
 4511,
 1467,
 11447,
 6031,
 1587,
 28675,
 559,
 2928,
 19193,
 10875,
 550,
 32077,
 893,
 57758,
 4794,
 5318,
 12148,
 1999,
 13075,
 1572,
 3224,
 1658,
 2190,
 3258,
 78586,
 2732,
 2114,
 11889,
 13983,
 1454,
 413,
 4812,
 2496,
 2775,
 1311,
 3176,
 9793,
 10257,
 15220,
 2637,
 83072,
 3570,
 353,
 8949,
 5856,
 3106,
 2595,
 75829,
 4379,
 18986,
 2743,
 3372,
 3335,
 1267,
 22156,
 14904,
 1198,
 5853,
 1703,
 1718,
 2213,
 1205,
 1302,
 3177,
 2058,
 1106,
 5980,
 2500,
 5308,
 11501,
 3095,
 2736,
 2153,
 2068,
 1143,
 2902,
 706,
 2980,
 2969,
 1049,
 1967,
 4103,
 20949,
 11412,
 2718,
 1733,
 12599,
 3188,
 3234,
 1961,
 1722,
 4417,
 1557,
 2764,
 2194,
 1252,
 24796,
 10059,
 604,
 1891,
 1128,
 7929,
 2697,
 950,
 3912,
 296,
 2990,
 1220,
 2450,
 1296,
 5185,
 4348,
 3171,
 1496,
 811,
 7532,
 1058,
 1307,
 3181,
 7560,
 8739,
 4177,
 873,
 2773,
 3316,
 418,
 1053,
 3148,
 10829,
 1117,
 1502,
 1229,
 2438,
 19227,
 95006,
 13,
 6211,
 13553,
 30933,
 538,
 6742,
 1026,
 3811,
 1996,
 829,
 8372,
 1197,
 256,
 128,
 18934,
 1910,
 99,
 1020,
 518,
 2163,
 1125,
 1855,
 1401,
 1884,
 2032,
 13685,
 2564,
 960,
 446,
 486,
 2002,
 3764,
 401,
 1279,
 2181,
 684,
 1448,
 807,
 7264,
 1022,
 5666,
 832,
 1511,
 4300,
 3067,
 468,
 1400,
 1133,
 14748,
 1394,
 1224,
 2952,
 4444,
 436733,
 1647,
 983,
 6990,
 1382,
 1668,
 62696,
 1590,
 560,
 2652,
 2104,
 1157,
 3921,
 3321,
 3508,
 727,
 1663,
 451,
 668,
 4195,
 2669,
 4917,
 831,
 3565,
 2128,
 40331,
 9805,
 7681,
 5007,
 50762,
 9858,
 1474,
 3071,
 3194,
 2382,
 2394,
 21851,
 11180,
 10017,
 4045,
 3586,
 1098,
 1352,
 1446,
 1001,
 1379,
 2436,
 2748,
 3132,
 1183,
 4415,
 15659,
 1240,
 1515,
 480,
 523,
 3100,
 1443,
 12988,
 23890,
 2449,
 15971,
 719,
 2040,
 536,
 4459,
 10271,
 1673,
 7602,
 1018,
 1525,
 1167,
 1533,
 1317,
 5164,
 50250,
 5925,
 25818,
 3161,
 34603,
 7412,
 905,
 1314,
 4691,
 1694,
 4104,
 11159,
 2686,
 1268,
 3091,
 4696,
 2467,
 3859,
 11383,
 3774,
 18736,
 6811,
 1717,
 2224,
 2081,
 7583,
 3595,
 21750,
 6485,
 3933,
 12618,
 5096,
 8486,
 3585,
 4480,
 3133,
 2209,
 2879,
 12335,
 3844,
 7195,
 3312,
 54466,
 12723,
 14871,
 88052,
 4577,
 1084,
 3908,
 11462,
 3675,
 7052,
 1618,
 4400,
 613,
 2192,
 2421,
 1829,
 1963,
 1325,
 15898,
 2462,
 1350,
 3698,
 2666,
 2716,
 1762,
 25783,
 4457,
 2064,
 2599,
 3539,
 2246,
 14474,
 1549,
 742,
 17973,
 1629,
 10277,
 3260,
 830,
 5465,
 2782,
 7209,
 2687,
 2528,
 3107,
 636,
 330,
 1270,
 1241,
 517,
 2041,
 9917,
 2050,
 1782,
 1616,
 1699,
 1246,
 875,
 1531,
 1233,
 1457,
 3651,
 1029,
 805,
 1356,
 1691,
 4122,
 1529,
 4633,
 718,
 690,
 1468,
 3732,
 1563,
 7167,
 840,
 979,
 629,
 787,
 930,
 941,
 1209,
 888,
 1501,
 1217,
 779,
 843,
 570,
 1310,
 1727,
 1610,
 8941,
 882,
 1393,
 3186,
 16070,
 1034,
 793,
 1136,
 1827,
 2445,
 3390,
 1168,
 914,
 851,
 963,
 3391,
 728,
 1914,
 627,
 33176,
 7503,
 1543,
 457,
 862,
 13153,
 2215,
 5999,
 585,
 1161,
 669,
 3230,
 3408,
 639,
 3086,
 885,
 1494,
 8145,
 631,
 1206,
 1313,
 771,
 1462,
 482,
 2708,
 1530,
 5499,
 281,
 416,
 2157,
 289,
 188,
 755,
 880,
 788,
 166,
 3338,
 3320,
 339,
 1780,
 732,
 7805,
 311,
 321,
 2221,
 643,
 3289,
 3263,
 2274,
 262,
 285,
 654,
 473,
 114,
 699,
 241,
 2905,
 389,
 180,
 1250,
 369,
 37119,
 387,
 238,
 2121,
 165,
 6941,
 304,
 1095,
 265,
 2860,
 2495,
 1178,
 965,
 403,
 2602,
 606,
 3442,
 591,
 277,
 850,
 1625,
 323,
 546,
 361,
 558,
 704,
 1698,
 810,
 268,
 6350,
 484,
 897,
 4353,
 682,
 4882,
 425,
 48040,
 2013,
 16865,
 246,
 564,
 406,
 438,
 189,
 2184,
 650,
 294,
 609,
 553,
 200,
 18099,
 2341,
 2441,
 2301,
 951,
 5477,
 3937,
 11000,
 2367,
 5674,
 3453,
 889,
 1784,
 2433,
 8127,
 1571,
 1554,
 3977,
 8720,
 616,
 1223,
 3470,
 2127,
 7028,
 2862,
 1427,
 1115,
 902,
 10507,
 1604,
 1039,
 30179,
 1687,
 5119,
 5151,
 919,
 955,
 1984,
 2594,
 4505,
 3196,
 1473,
 4030,
 11144,
 4010,
 2099,
 2322,
 5394,
 1875,
 673,
 5729,
 77384,
 5213,
 15218,
 4133,
 1675,
 7297,
 1952,
 1051,
 1412,
 3203,
 1831,
 3090,
 1176,
 3140,
 1083,
 7741,
 2604,
 1057,
 8192,
 1697,
 2297,
 1995,
 2867,
 886,
 2482,
 ...]

In [154]:
df.head()

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,40-49,40-49 y/o % of total pop,50-59,50-59 y/o % of total pop,60-69,60-69 y/o % of total pop,70-79,70-79 y/o % of total pop,80+,80+ y/o % of total pop,White-alone pop,% White-alone,Black-alone pop,% Black-alone,Native American/American Indian-alone pop,% NA/AI-alone,Asian-alone pop,% Asian-alone,Hawaiian/Pacific Islander-alone pop,% Hawaiian/PI-alone,Two or more races pop,% Two or more races,POP_ESTIMATE_2018,N_POP_CHG_2018,GQ_ESTIMATES_2018,R_birth_2018,R_death_2018,R_NATURAL_INC_2018,R_INTERNATIONAL_MIG_2018,R_DOMESTIC_MIG_2018,R_NET_MIG_2018,Less than a high school diploma 2014-18,High school diploma only 2014-18,Some college or associate's degree 2014-18,Bachelor's degree or higher 2014-18,Percent of adults with less than a high school diploma 2014-18,Percent of adults with a high school diploma only 2014-18,Percent of adults completing some college or associate's degree 2014-18,Percent of adults with a bachelor's degree or higher 2014-18,POVALL_2018,PCTPOVALL_2018,PCTPOV017_2018,PCTPOV517_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Active Physicians per 100000 Population 2018 (AAMC),Total Active Patient Care Physicians per 100000 Population 2018 (AAMC),Active Primary Care Physicians per 100000 Population 2018 (AAMC),Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC),Active General Surgeons per 100000 Population 2018 (AAMC),Active Patient Care General Surgeons per 100000 Population 2018 (AAMC),Total nurse practitioners (2019),Total physician assistants (2019),Total Hospitals (2019),Internal Medicine Primary Care (2019),Family Medicine/General Practice Primary Care (2019),Total Specialist Physicians (2019),ICU Beds_x,Total Population,Population Aged 60+,Percent of Population Aged 60+,COUNTY_NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,county_pop2018_18 and older,anycondition_prevalence,anycondition_Lower 95% CI,anycondition_Upper 95% CI,anycondition_number,Obesity_prevalence,Obesity_Lower 95% CI,Obesity_Upper 95% CI,Obesity_number,Heart disease_prevalence,Heart disease_Lower 95% CI,Heart disease_Upper 95% CI,Heart disease_number,COPD_prevalence,COPD_Lower 95% CI,COPD_Upper 95% CI,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
0,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,7582,13.636445,7738,13.917016,5826,10.478229,4050,7.284042,2014,3.622237,42660,76.725239,10915,19.630942,267,0.480207,681,1.224798,62,0.111509,1016,1.827305,55601,158,455,11.8,9.6,2.2,0.0,0.7,0.6,4204,12119,10552,10291,11.3,32.6,28.4,27.7,7587,13.8,19.3,19.5,59338,53628,65048,25957,25015,942,3.6,59338,119.0,217.1,196.7,77.2,71.2,7.6,6.9,28.859137,6.085786,1.148905,25.992561,21.249061,72.142154,6,55036,10523,19.1,Autauga,Alabama,1,1,42438,47.6,45.4,49.4,20181,35.8,34.2,37.3,15193,7.9,7.2,8.7,3345,8.6,7.3,9.9,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
1,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,27338,12.539102,29986,13.753658,29932,13.728890,20936,9.602701,9368,4.296814,190301,87.285228,19492,8.940382,1684,0.772399,2508,1.150343,146,0.066966,3891,1.784682,218022,5403,2190,10.5,10.3,0.1,0.5,24.3,24.8,14310,40579,46025,46075,9.7,27.6,31.3,31.3,21069,9.8,13.9,13.1,57588,54437,60739,93849,90456,3393,3.6,57588,115.5,217.1,196.7,77.2,71.2,7.6,6.9,113.162114,23.863512,4.505074,101.921730,83.321572,282.882982,51,203360,53519,26.3,Baldwin,Alabama,1,3,170912,40.2,38.2,42.3,68790,29.7,28.4,31.0,50761,7.8,7.0,8.7,13414,8.6,7.2,10.1,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
2,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,3074,12.354809,3278,13.174712,3076,12.362847,2244,9.018930,1048,4.212049,12209,49.069571,12042,48.398376,164,0.659137,113,0.454162,46,0.184880,307,1.233873,24881,-277,2820,10.4,12.9,-2.5,0.5,-9.1,-8.6,4901,6486,4566,2220,27.0,35.7,25.1,12.2,6788,30.9,43.9,36.7,34382,31157,37607,8373,7940,433,5.2,34382,68.9,217.1,196.7,77.2,71.2,7.6,6.9,12.914231,2.723340,0.514126,11.631462,9.508784,32.283033,5,26201,6150,23.5,Barbour,Alabama,1,5,19689,57.5,55.6,59.1,11325,40.7,39.5,41.9,8013,11.0,10.1,11.8,2159,12.1,10.7,13.3,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
3,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,3038,13.562500,3115,13.906250,2545,11.361607,1723,7.691964,785,3.504464,17211,76.834821,4770,21.294643,98,0.437500,53,0.236607,26,0.116071,242,1.080357,22400,-155,2151,11.1,11.4,-0.3,0.4,-7.0,-6.6,2650,7471,3846,1813,16.8,47.3,24.4,11.5,4400,21.8,27.8,26.3,46064,41283,50845,8661,8317,344,4.0,46064,92.3,217.1,196.7,77.2,71.2,7.6,6.9,11.626493,2.451783,0.462860,10.471635,8.560619,29.063942,0,22580,4773,21.1,Bibb,Alabama,1,7,17813,51.6,49.6,53.4,9190,38.7,37.4,40.2,6894,8.6,7.9,9.3,1533,10.0,8.8,11.3,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
4,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,7474,12.921853,7844,13.561549,6965,12.041840,4931,8.525242,2335,4.036999,55456,95.878285,950,1.642462,378,0.653527,185,0.319848,70,0.121024,801,1.384855,57840,13,489,11.8,11.4,0.3,0.1,-0.2,0.0,7861,13489,13267,5010,19.8,34.0,33.5,12.6,7527,13.2,18.0,15.5,50412,46157,54667,25006,24128,878,3.5,50412,101.1,217.1,196.7,77.2,71.2,7.6,6.9,30.021267,6.330854,1.195171,27.039257,22.104740,75.047251,6,57667,13600,23.6,Blount,Alabama,1,9,44448,46.3,44.3,48.4,20584,34.0,32.4,35.5,15112,9.2,8.4,10.1,4101,10.5,9.1,12.0,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2

In [155]:
df.rename(columns={'19-Oct': '10-19'}, inplace = True)

In [156]:
df['10-19']

0        7637
1       26913
2        2960
3        2596
4        7570
        ...
3135     6326
3136     2185
3137     3205
3138     1113
3139      779
Name: 10-19, Length: 3140, dtype: int64

## MinMaxScaler

In [157]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
                    
features = ['0-9', '10-19', '20-29','30-39', '40-49', '50-59', '60-69', '70-79', '80+', 'diabetes_number']
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(df[features])

data_scaled = pd.DataFrame(features_scaled, index=df.index, columns= features)
data_scaled.head()

,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80+,diabetes_number
0,0.005617,0.006163,0.004417,0.004713,0.005613,0.005914,0.005724,0.007063,0.005653,0.005724
1,0.020490,0.021719,0.015143,0.016781,0.020246,0.022950,0.029490,0.036557,0.026294,0.021536
2,0.002261,0.002389,0.002099,0.002124,0.002274,0.002499,0.003013,0.003909,0.002942,0.004052
3,0.002033,0.002095,0.001945,0.002065,0.002247,0.002374,0.002489,0.002999,0.002203,0.002625
4,0.005872,0.006109,0.004330,0.004576,0.005533,0.005995,0.006847,0.008602,0.006554,0.006307

In [158]:
from sklearn.model_selection import train_test_split

X = data_scaled.drop('diabetes_number', axis=1)
y = data_scaled['diabetes_number']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [159]:
X_train['diabetes_number'] = y_train.values
X_test['diabetes_number'] = y_test.values

In [160]:
X_train.head()

,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80+,diabetes_number
1292,0.002666,0.002795,0.001877,0.001876,0.002094,0.002923,0.003786,0.004286,0.003391,0.002953
2302,0.004363,0.004641,0.003299,0.003549,0.004352,0.006027,0.008135,0.008375,0.008218,0.005676
761,0.003240,0.004130,0.003983,0.002898,0.003294,0.003900,0.004268,0.004728,0.004381,0.003872
2194,0.009239,0.010205,0.007447,0.007555,0.008474,0.009770,0.010619,0.011755,0.009762,0.008298
1241,0.013820,0.014257,0.011098,0.010642,0.011733,0.013758,0.016651,0.017585,0.016950,0.013626

In [161]:
X_test.head()

,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80+,diabetes_number
2893,0.000672,0.000729,0.000711,0.000826,0.000896,0.000959,0.001079,0.001378,0.001620,0.001151
2968,0.025527,0.024168,0.026632,0.024056,0.022145,0.026777,0.034480,0.037981,0.027445,0.022856
1064,0.001718,0.001718,0.001441,0.001603,0.001792,0.001779,0.001865,0.002332,0.001476,0.002723
1231,0.012563,0.012825,0.008699,0.009365,0.010526,0.012865,0.014825,0.014752,0.011497,0.009888
2987,0.020274,0.021830,0.026017,0.018913,0.018823,0.020179,0.027425,0.030236,0.023224,0.017799

In [162]:
X_train.to_csv('../data/processed/data_train.csv', index = False)
X_test.to_csv('../data/processed/data_test.csv', index = False)

## Regression models

In [163]:
data_train = pd.read_csv('../data/processed/data_train.csv')
data_test = pd.read_csv('../data/processed/data_test.csv')

In [164]:
data_train.head()

,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80+,diabetes_number
0,0.002666,0.002795,0.001877,0.001876,0.002094,0.002923,0.003786,0.004286,0.003391,0.002953
1,0.004363,0.004641,0.003299,0.003549,0.004352,0.006027,0.008135,0.008375,0.008218,0.005676
2,0.003240,0.004130,0.003983,0.002898,0.003294,0.003900,0.004268,0.004728,0.004381,0.003872
3,0.009239,0.010205,0.007447,0.007555,0.008474,0.009770,0.010619,0.011755,0.009762,0.008298
4,0.013820,0.014257,0.011098,0.010642,0.011733,0.013758,0.016651,0.017585,0.016950,0.013626

In [165]:
X_train = data_train.drop(['diabetes_number'], axis=1)
y_train = data_train['diabetes_number']
X_test = data_test.drop(['diabetes_number'], axis= 1)
y_test = data_test['diabetes_number']

In [166]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

models = [LinearRegression, Lasso, Ridge]

for selected_model in models:
    if selected_model == LinearRegression:
        model = LinearRegression()
    else:
        model = selected_model(alpha=10)
    model.fit(X_train,y_train)

## Prediction

In [167]:
y_pred = model.predict(X_test)
y_pred

array([0.00319525, 0.02175445, 0.00372592, 0.01085699, 0.01847459,
       0.00443589, 0.0034232 , 0.00350358, 0.0028979 , 0.00355249,
       0.00402355, 0.00267198, 0.0095156 , 0.00373052, 0.01455466,
       0.00533772, 0.0676636 , 0.00379111, 0.00432779, 0.00296331,
       0.00407243, 0.00323874, 0.00350856, 0.00304565, 0.13603797,
       0.00670261, 0.00378991, 0.00504834, 0.00358523, 0.00268818,
       0.0034572 , 0.00429713, 0.00503917, 0.005832  , 0.01323004,
       0.00389763, 0.0053598 , 0.0041308 , 0.00341185, 0.0053418 ,
       0.003879  , 0.01575149, 0.00292714, 0.00265481, 0.00631348,
       0.00312011, 0.00285405, 0.01022783, 0.0034279 , 0.00307589,
       0.01994685, 0.00273968, 0.00436484, 0.00305486, 0.01315207,
       0.00326515, 0.04732032, 0.00488497, 0.00605502, 0.00341173,
       0.01469416, 0.00274055, 0.00301222, 0.01678093, 0.00450666,
       0.0069426 , 0.00335517, 0.00438975, 0.00292281, 0.02818198,
       0.00506193, 0.00378888, 0.00419176, 0.00431739, 0.00438127,
       0.00734548, 0.02857893, 0.00408245, 0.00288558, 0.00317013,
       0.00408442, 0.00909331, 0.01850223, 0.00254015, 0.00304018,
       0.00351828, 0.06915386, 0.00368794, 0.00485994, 0.01732343,
       0.00330781, 0.00275006, 0.00364025, 0.00508412, 0.00348929,
       0.00449815, 0.00395441, 0.00317565, 0.0152988 , 0.00256431,
       0.04927823, 0.01344717, 0.00436376, 0.00268943, 0.00290775,
       0.00567151, 0.00560988, 0.00543494, 0.01338974, 0.02230814,
       0.00256531, 0.01110497, 0.03174881, 0.00719525, 0.00329873,
       0.07862129, 0.00352756, 0.00305391, 0.01217801, 0.0045847 ,
       0.00319179, 0.00412773, 0.00329015, 0.00614073, 0.004028  ,
       0.0041677 , 0.00871714, 0.00513803, 0.01666873, 0.00677606,
       0.00322308, 0.00273031, 0.00614555, 0.0025674 , 0.00624294,
       0.00439792, 0.00355321, 0.02510677, 0.00608279, 0.0034424 ,
       0.00448648, 0.00350536, 0.07481295, 0.00406444, 0.00295004,
       0.00326202, 0.00386377, 0.00265634, 0.00874476, 0.00383805,
       0.00338221, 0.09214089, 0.00394002, 0.00596403, 0.00315361,
       0.00351924, 0.0026914 , 0.00336532, 0.01162466, 0.00315877,
       0.00466098, 0.00379633, 0.0033174 , 0.00274759, 0.00442273,
       0.00660625, 0.00393216, 0.01392085, 0.01808856, 0.00319568,
       0.00467334, 0.01744933, 0.00318907, 0.00371736, 0.00790903,
       0.00448324, 0.00550409, 0.00889199, 0.00644152, 0.00446141,
       0.00441212, 0.00341975, 0.00305541, 0.00399227, 0.00312824,
       0.00289394, 0.00411015, 0.00576695, 0.0051128 , 0.00359639,
       0.01279273, 0.00321323, 0.00361459, 0.00287633, 0.00480879,
       0.00297988, 0.00321556, 0.00568739, 0.00343255, 0.00281721,
       0.01688736, 0.01028572, 0.11655983, 0.00368394, 0.00723268,
       0.00358248, 0.00411579, 0.00595012, 0.00602997, 0.00354726,
       0.00275066, 0.00333225, 0.00496721, 0.00569778, 0.00419239,
       0.0184526 , 0.00266478, 0.00388761, 0.00312418, 0.02287178,
       0.00322682, 0.00469588, 0.00430944, 0.00388129, 0.01551364,
       0.00297111, 0.0115724 , 0.00344507, 0.00262801, 0.00454   ,
       0.00298676, 0.00454841, 0.00348576, 0.00510204, 0.00401881,
       0.00317578, 0.00462382, 0.00363392, 0.00345047, 0.01659347,
       0.00616549, 0.00282289, 0.00309929, 0.00427061, 0.00357447,
       0.00308595, 0.00714065, 0.002649  , 0.0441574 , 0.00329774,
       0.00308148, 0.00342695, 0.00297444, 0.00415597, 0.03199109,
       0.00279881, 0.00313501, 0.01207761, 0.00285766, 0.00723757,
       0.0030286 , 0.00262664, 0.00522121, 0.0035292 , 0.00420076,
       0.00643353, 0.00418839, 0.00404335, 0.00266506, 0.00527494,
       0.00638274, 0.00484307, 0.00929205, 0.00371209, 0.00415319,
       0.00270817, 0.00676783, 0.00643752, 0.00260817, 0.00272746,
       0.02937819, 0.01509493, 0.00431477, 0.00307921, 0.00365532,
       0.00265645, 0.00352934, 0.00344588, 0.00480748, 0.01885567,
       0.00346135, 0.00960567, 0.003261  , 0.00288519, 0.01632745,
       0.00292887, 0.01503236, 0.02031528, 0.00311401, 0.00306504,
       0.01018834, 0.00348503, 0.0046806 , 0.00265625, 0.00344483,
       0.00313819, 0.00347827, 0.00494559, 0.03272092, 0.00820584,
       0.00428775, 0.00326633, 0.00690163, 0.00510495, 0.00386904,
       0.01909003, 0.00450974, 0.00448378, 0.00292797, 0.00301191,
       0.00339844, 0.00307292, 0.00285199, 0.00291389, 0.00287357,
       0.01099995, 0.00313516, 0.00443984, 0.00312974, 0.01305516,
       0.00449121, 0.01003884, 0.01755404, 0.00300669, 0.003913  ,
       0.00325931, 0.00834571, 0.00703382, 0.00999203, 0.00333108,
       0.00324949, 0.00317236, 0.00513503, 0.00435553, 0.0073281 ,
       0.00408214, 0.00267623, 0.00298022, 0.00339267, 0.00287356,
       0.00368813, 0.008144  , 0.00458422, 0.01353368, 0.00712786,
       0.00390611, 0.00431897, 0.00390611, 0.00341189, 0.00739515,
       0.00325302, 0.00264725, 0.00494065, 0.00327101, 0.00303216,
       0.00332222, 0.02308471, 0.02512344, 0.00297692, 0.00373645,
       0.00442757, 0.00887313, 0.0029366 , 0.00474943, 0.05539614,
       0.00968085, 0.00453887, 0.00283562, 0.01858215, 0.00376794,
       0.00418815, 0.00798097, 0.03350116, 0.01409921, 0.00273353,
       0.00359804, 0.00407526, 0.00357172, 0.00650481, 0.00575785,
       0.00629503, 0.00508708, 0.00513356, 0.00271715, 0.00327201,
       0.00597936, 0.00429964, 0.00443185, 0.00352369, 0.0027866 ,
       0.00453656, 0.00430893, 0.00732085, 0.00523915, 0.03928983,
       0.003647  , 0.00408279, 0.0059862 , 0.0025796 , 0.00961791,
       0.00313443, 0.00347809, 0.00269632, 0.00279097, 0.00353794,
       0.08914556, 0.00452029, 0.00724676, 0.00372007, 0.006471  ,
       0.00407976, 0.01152593, 0.003839  , 0.00819585, 0.0032744 ,
       0.01830135, 0.00351889, 0.01009137, 0.00327557, 0.04949392,
       0.00525025, 0.00341166, 0.0051148 , 0.00298792, 0.00696397,
       0.00447781, 0.00299942, 0.00374934, 0.0425142 , 0.06409187,
       0.00314   , 0.00589073, 0.00426518, 0.0197138 , 0.00322002,
       0.00877266, 0.00291602, 0.00369336, 0.00306368, 0.00358187,
       0.00361737, 0.00293797, 0.00336591, 0.00382639, 0.00595068,
       0.01436639, 0.00538248, 0.00519568, 0.00885307, 0.00476316,
       0.03181439, 0.00340725, 0.00418697, 0.0058483 , 0.00296833,
       0.00323597, 0.00585009, 0.00392655, 0.00822551, 0.00419141,
       0.00401267, 0.01084706, 0.00408967, 0.00295252, 0.00339621,
       0.00422046, 0.00269386, 0.00443778, 0.00578019, 0.00479215,
       0.00625787, 0.00287495, 0.00321578, 0.002879  , 0.02418804,
       0.00356607, 0.00660047, 0.00281517, 0.01092861, 0.00600354,
       0.01173739, 0.01061266, 0.00333135, 0.00391749, 0.00418465,
       0.04979268, 0.00454452, 0.00348906, 0.06263546, 0.0039233 ,
       0.00260483, 0.0402052 , 0.01048847, 0.00310233, 0.00341474,
       0.00597147, 0.00410268, 0.00845176, 0.00680199, 0.0044156 ,
       0.00396782, 0.00482453, 0.00408074, 0.0080457 , 0.00467093,
       0.00629582, 0.00580021, 0.00713882, 0.01229995, 0.00285558,
       0.00505701, 0.00328671, 0.00257018, 0.00376864, 0.01830031,
       0.00359154, 0.00980609, 0.02075982, 0.00294704, 0.00720028,
       0.00477985, 0.00567624, 0.00285135, 0.00539753, 0.0068441 ,
       0.00401022, 0.00444445, 0.00374614, 0.02690457, 0.03628724,
       0.00753349, 0.00317615, 0.00650356, 0.06067442, 0.00320249,
       0.01872341, 0.00354032, 0.00689789, 0.00800725, 0.00313545,
       0.00460898, 0.00673129, 0.00574578, 0.00446828, 0.00641257,
       0.00385641, 0.00782295, 0.00367238, 0.00908102, 0.03310168,
       0.00394943, 0.00600456, 0.11091555, 0.00504322, 0.00303572,
       0.0108519 , 0.04023687, 0.00874171, 0.00496864, 0.00328284,
       0.00604325, 0.00344934, 0.00299853, 0.00375285, 0.00306242,
       0.02603001, 0.00451037, 0.00338303, 0.00337978, 0.00664948,
       0.00357729, 0.00494996, 0.00288589, 0.00439562, 0.00335309,
       0.0041082 , 0.00258108, 0.00818549, 0.00382958, 0.0136258 ,
       0.0104807 , 0.00301169, 0.00279226, 0.02751978, 0.03580229,
       0.00476566, 0.00290556, 0.00601117, 0.00646437, 0.00454471,
       0.00317332, 0.01304081, 0.00309151, 0.01306436, 0.00386212,
       0.00295602, 0.02324153, 0.00367559, 0.01094685, 0.00866806,
       0.00257029, 0.00483905, 0.01461676, 0.00271422, 0.0033993 ,
       0.00329539, 0.00291297, 0.01675846, 0.00395122, 0.00278264,
       0.00302198, 0.01453009, 0.0027389 , 0.00457323, 0.00294595,
       0.00555912, 0.00950065, 0.00588222])

In [168]:
from sklearn.metrics import mean_squared_error, r2_score

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean squared error:', mean_squared_error(y_test, y_pred))

R2 Score:  0.909898220315607
Mean squared error: 2.8811020491796996e-05

- This r2 score indicates that the regression model explains about 97.5% of the variance in the target variable. This suggests that the model provides a very good fit to the data.

- This mean squared error indicates that, on average, the squared difference between the actual values and the predicted values by the model is extremely small. This suggests that the model's predictions are very close to the actual values, with very little error

### The coefficients and intercept

In [169]:
print('Coefficients:', model.coef_)
print('Intercept:', model.intercept_)

Coefficients: [0.080754   0.07873781 0.07377564 0.07531927 0.07499928 0.07575902
 0.07788328 0.07978426 0.07640085]
Intercept: 0.002511489292713066